[phases.setup]
nixPkgs = ["jdk21", "gradle"]

[phases.build]
cmds = ["gradle clean bootJar -x test --no-daemon"]

[start]
cmd = "java -Dserver.port=$PORT $JAVA_OPTS -jar build/libs/gym-management-0.0.1-SNAPSHOT.jar"
